/* should pass syntax check */

int i1;
char c1;
void v1;

int i2[17];
char c2[17];
void v2[17];

void foo (int i3[], char c3, void v3) { 
  int i4;
  char c4;
  void v4;
  
  {
    i = "rashmi";
  }

  c[17] = 1;
  
  if (i >= 1){  
     i = 'z'; 
  }

  if (i <= 17){
    i = 2;
  }
  else{
    if (i == 0){
      i = c + 17;
    }
 }
  while (v > 17 ) 
    v = 13;

  return 0;
}


int main() {
  foo(i, x + y, foo());
  return;
}
